spring:
 application:
  name: CONFIG-FILE

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
     defoultZone:
      http://localhost:8761/eureka
